#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for xAI and OpenRouter Provider Implementation

set -e

echo "========================================"
echo "ClippyJS AI Provider Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to project root
cd "$(dirname "$0")/../../.."

echo ""
echo -e "${YELLOW}Step 1: Installing workspace dependencies...${NC}"
yarn install

echo ""
echo -e "${YELLOW}Step 2: Building ai package (dependency)...${NC}"
cd packages/ai && yarn build
cd ../..

echo ""
echo -e "${YELLOW}Step 3: Building ai-openai package (reference)...${NC}"
cd packages/ai-openai && yarn build
cd ../..

# Check if new packages exist
if [ -d "packages/ai-xai" ]; then
    echo ""
    echo -e "${YELLOW}Step 4a: Installing ai-xai dependencies...${NC}"
    cd packages/ai-xai && yarn install
    cd ../..
fi

if [ -d "packages/ai-openrouter" ]; then
    echo ""
    echo -e "${YELLOW}Step 4b: Installing ai-openrouter dependencies...${NC}"
    cd packages/ai-openrouter && yarn install
    cd ../..
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "New Package Directories:"
echo "  @clippyjs/ai-xai:        packages/ai-xai/"
echo "  @clippyjs/ai-openrouter: packages/ai-openrouter/"
echo ""
echo "Reference Implementation:"
echo "  @clippyjs/ai-openai:     packages/ai-openai/"
echo ""
echo "Commands:"
echo "  Build:     yarn build"
echo "  Test:      yarn test"
echo "  Typecheck: yarn typecheck"
echo ""
echo "API Endpoints:"
echo "  xAI:        https://api.x.ai/v1"
echo "  OpenRouter: https://openrouter.ai/api/v1"
echo ""
